version: '3.0' # Note that the verison is NOT for this document, but for the version of docker-compose itself. Keep.
services:
  eol-repo-elasticsearch:
    image: elasticsearch:6.4.0
    container_name: harv_search
    restart: always
    environment:
      - RAILS_ENV
      - bootstrap.memory_lock=true
      - cluster.name=eol-search-${RAILS_ENV}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./templates/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/eol-repo-elasticsearch/data:/var/data/elasticsearch
      - /data/eol-repo-elasticsearch/log:/var/log/elasticsearch
    networks:
      - docker_eolnet
    ports:
      - 9200:9200
      - 9300:9300
  eol-repo-elasticsearch2:
    image: elasticsearch:6.4.0
    container_name: harv_search2
    environment:
      - RAILS_ENV
      - cluster.name=eol-search-${RAILS_ENV}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=[eol-backend-elasticsearch,eol-backend-elasticsearch3]"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./templates/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/eol-repo-elasticsearch2/data:/var/data/elasticsearch
      - /data/eol-repo-elasticsearch2/log:/var/log/elasticsearch
    networks:
      - docker_eolnet
  eol-repo-elasticsearch3:
    image: elasticsearch:6.4.0
    container_name: harv_search3
    environment:
      - cluster.name=eol-search-${RAILS_ENV}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=[eol-backend-elasticsearch,eol-backend-elasticsearch2]"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./templates/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/eol-repo-elasticsearch3/data:/var/data/elasticsearch
      - /data/eol-repo-elasticsearch3/log:/var/log/elasticsearch
    networks:
      - docker_eolnet
  eol-repo-memcached:
    image: memcached
    container_name: harv_cache
    restart: always
    environment:
      - TZ=America/New_York
    command: memcached -m 4096m
    networks:
      - docker_eolnet
  eol-repo-mysql:
    image: mysql:5.7.12
    container_name: harv_db
    restart: always
    env_file:
      - resources/staging.env
    volumes:
      - /data/eol-repo-mysql:/var/lib/mysql
    networks:
      - docker_eolnet
  eol-repo-app:
    build: ..
    image: harvester_v3
    container_name: harv_app
    restart: always
    volumes:
      - ./resources/secrets.yml:/app/config/secrets.yml
      - /data/eol-repo-app:/app/public/data
      - /data/eol-repo-app/tmp:/tmp
      - /eol/tmp/harvester:/tmp
    depends_on:
      - eol-repo-elasticsearch
      - eol-repo-mysql
      - eol-repo-memcached
    links:
      - eol-repo-elasticsearch:elasticsearch
      - eol-repo-memcached:memcached
      - eol-repo-mysql:mysql
    env_file:
      - resources/staging.env
    ports:
      - 3001:3000
    networks:
      - docker_eolnet
networks:
  docker_eolnet:
    external: true
